### PR TITLE
lowered sleep times to speed up initialization

### PR DESCRIPTION
**Pull request by danielskowronski**

### CODE REVIEW

**Comment by danielskowronski** [comment]
We could also have wiki updated to have something like

> You need to have provider's original software installed and running. For example for Corsair iCUE you need iCUE.exe to be running in background - Initialize() waits for each provider's executable to be running.

I spent nearly hour discovering my VisualStudio skills are bit outdated while forking this repo and importing *csproj*s to investigate why project that uses RGBKit hangs forever ;)

**Comment by AndrewBabbitt97** [comment]
I have been thinking that maybe we want to change it so providers should skip init if the software for it isn't installed. AURA should just throw a COM exception of it's missing right now. Checking if the service files at least exist would be useful.

On the note of the PR, I'm okay with the 1000 ms -> 100 Ms changes. However, the 30000 Ms changes are not okay. I have seen issues with AURA and CUE not having all devices initialized on their end. I have seen things such as a single ram stick missing and sometimes not getting any devices in the case of CUE.

I want to find a better solution than to just sleep, but it's up to the RGB Software to initialize itself and we have no callback to know when that's done before we load the device list.

Perhaps if we did a periodic refresh in the health check to update the device list, I just want to be weary of the perf overhead on this. I haven't profiled CPU usage when init is happening.

**Comment by danielskowronski** [comment]
Uh, can't help much with missing device - I got only single iCUE keyboard and Aura mobo with 2 regions plus LED stripes; didn't get anything missing.
Maybe the issue is that SDK can't be reliably called in some time after service starts - then it works fine? Will have to check.

**Comment by AndrewBabbitt97** [comment]
The reason why it's 30 seconds is because it's inconsistent. 30 seconds was a decent amount of time for the services/processes to actually start.

This isn't usually an issue for apps that are run by a user but are when an app runs on PC startup before the CUE/AURA services have fully started.

This is why we wait for both processes to be running then have a delay after. Just because a process has started does not mean it is ready to be used. If it's not ready it may not report back all devices, this causing some devices not to be available to control.

**Pull request closed without merging**
